server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512
          jwk-set-uri: https://idp.example.org/.well-known/jwks.json

# JWT Configuration
jwt:
  jwks-uri: http://localhost:9000/oauth2/jwks
  type: JWT
  version: "1"

# Clear, explicit logging configuration
logging:
  level:
    com:
      github:
        TsutomuNakamura:
          '[oauth2_authorization_server_for_client_credentials]': INFO
    org:
      springframework:
        security:
          oauth2: INFO
        web: WARN
        boot:
          actuate: WARN
      apache:
        catalina: WARN
